package a

// The analyzer's contract ("reports every package-level func init")
// deliberately grants NO test-file exemption: implicit initialization harms
// test determinism exactly as it harms production code, so an init in a
// _test.go file is flagged like any other.
//
// Harness limitation: that case cannot be encoded as a literal _test.go file
// here. analysistest (x/tools v0.47.0) loads testdata with packages.Config
// Tests: true, and the moment a _test.go file exists it also loads the
// synthesized "a.test" main package, whose generated _testmain.go itself
// contains a func init ("Code generated by 'go test'. DO NOT EDIT."). The
// analyzer flags that init too, and a generated file can never carry an
// expectation comment, so the harness fails with an unmatchable "unexpected
// diagnostic". This ordinary file therefore stands in for the test-file case:
// same package-level init shape, same required diagnostic.
func init() { _ = 0 } // want `func init is not permitted`
